version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenwaze raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenwaze
        columns:
          - name: "orders_id||pdt_id"
            description: date of purchase 
            tests:
              - not_null
              - unique
            freshness:
             warn_after:{90}                
            loaded_at_field: "cast(date_date as timestamp)"
                  
            
                 
            
      - name: product
        identifier: raw_gz_product
        description: product related information of greenwaze
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
                  
                  

      - name: ship
        identifier: raw_gz_ship 
        description: shipment information of greenwaze
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
                  
              
 