version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenwaze raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenwaze
        columns:
          - name: "orders_id||pdt_id"
            description: date of purchase 
            tests:
              - not_null
              - unique
         
               
         
                
            
      - name: product
        identifier: raw_gz_product
        description: product related information of greenwaze
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
                  
                  

      - name: ship
        identifier: raw_gz_ship 
        description: shipment information of greenwaze
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date || campaign_key
            tests:
              - unique
              - not_null
      
     
                 
                  
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date || campaign_key
            tests:
              - unique
              - not_null

      - name: creiteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date || campaign_key
            tests:
              - unique
              - not_null

      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date || campaign_key
            tests:
              - unique
              - not_null


models:
  - name: int_campaigns_day
    tests:
      - unique:
           column_name: date_date
      - not_null:
            column_name: date_date

            
models:
  - name: finance_campaigns_day
    tests:
      - unique:
           column_name: date_date
      - not_null:
            column_name: date_date

          
        


      
    
    
   


     
 